from config.config import TrainConfig
from config.callback_cfg import CallbackConfigurator
from config.model_cfg import ModelConfigurator
from config.optimizer_cfg import OptimizerConfigurator
from config.metrics_cfg import MetricsConfigurator