training_cfg:
    mode: "2d"
    epochs: 50
    batch_size: 10
    loss: "binary_crossentropy"
#    class_weights:
#        0: 05966296
#        1: 1.0
    pos_weight: 10.82
    track_metrics:
        - "accuracy"
        - "jaccard_index"
        - "dice_coefficient"

optimizer_cfg:
    # args in tf.KERAS.OPTIMIZERS api docs
    optimizer: "adam"
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
    epsilon: 0.0000001
    amsgrad: false

model_cfg:
    model: "resunet2d"
    crop_shape: [256, 256]
    unet_depth: 2
    base_filters: 16
    batch_normalization: true
    transposed_convolution: false
    residual_preactivation: true

dataset_cfg:
#     dataset_path : "/mnt/ssd1/datasets/em_neuroseg"
     dataset_path : "/home/phil/Scrivania/spim_dataset"
#     dataset_path : "/home/phil/repos/neuroseg/neuroseg/tests/test_datasets/stack_1ch"
     mode: "single_images"
     n_channels: 2
     positive_class_value: 255
     negative_class_value: 0
     ignore_last_channel: true
     use_bboxes: true

output_cfg:
#    output_path: "/mnt/ssd1/em_training"
    output_path: "/home/phil/Scrivania/single_images_test_out"
    descriptor_path: "/home/phil/Scrivania/single_images_test_descr"
#    descriptor_path: "/mnt/ssd1/em_training/descr"
    enable_wandb_tracking: false
    extra_padding_windows: 2

data_augmentation_cfg:
    debug_mode: false
    single_thread:  true
    threads: 6
    buffer_size : 1000
    shuffle: false
    seed: 123
    # pre_crop_scales: [1.1, 1.1, 1.1]
    transform_cfg:
        spatial_transform:
            do_elastic_deform: true
            deformation_scale: [0, 0.25, 0.25]
            do_rotation: true
            angle_x: [-0.314, 0.314]
            angle_y: [0, 6.38]
            angle_z: [0, 6.38]
            p_rot_per_sample: 0.15
            do_scale: true
            scale: [0.95, 1.05]
            border_mode_data: "reflect"
            random_crop: true

        brightness_transform:
            mu: 0
            sigma: 0.01
            p_per_sample: 0.15

        brightness_multiplicative_transform:
            multiplier_range: [0.9, 1.1]
            per_channel: true
            p_per_sample: 0.15

        rot90_transform:
            p_per_sample: 0.15
            num_rot : [1, 2, 3]
#            axes: [0, 1, 2]

        mirror_transform:
            axes: [0, 1, 2]

        gamma_transform:
            gamma_range: [0.9, 1.1]
            invert_image: false
            per_channel: true
            p_per_sample: 0.15
#            retain_stats: true

        gaussian_noise_transform:
            noise_variance: [0, 0.00005]
            p_per_sample:  0.15

#        gaussian_blur_transform:
#            p_per_sample: 0.15
#            blur_sigma: [1, 1.5]
#            different_sigma_per_channel: true,
#            p_per_channel: 1

performance_evaluation_cfg:
    window_size: [256, 256]
    batch_size:       15
    chunk_size:       20
    classification_threshold:   0.5
    add_empty_channel:          true
    enable_curves: false

callbacks_cfg:
    checkpoint:
        monitor:        "val_loss"
        verbose:        1
        save_best_only: false
        mode:           "min"

    csvlogger:
        append:     true
        separator: ";"

    reducelronplateau:
        factor:     0.1
        patience:   5
        min_lr:     0.00000000067
        verbose:    1

notes: ""

debug_cfg:
    test_datagen_inspector: false
    train_datagen_inspector: false
    val_datagen_inspector: false

tiled_predictor_cfg:
    extra_padding_windows: 2
#    window_overlap : [12, 12]
    tiling_mode: "drop_borders"