training_cfg:
    mode: "2d"
    epochs: 1
    batch_size: 20
    loss: "weighted_binary_crossentropy"

    # pos_weight: 5
    class_weights: [1., 5.]
    track_metrics:
        - "accuracy"
        - "jaccard_index"
        - "dice_coefficient"
    enable_wandb_tracking: false
    wandb_project: "unet2d_spim"
    wandb_entity: "filippocastelli"

optimizer_cfg:
    # args in tf.KERAS.OPTIMIZERS api docs
    optimizer: "adam"
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
    epsilon: 0.0000001
    amsgrad: false

model_cfg:
    model: "resunet2d"
    window_size: [256, 256]
    unet_depth: 2
    base_filters: 16
    batch_normalization: true
    transposed_convolution: false
    residual_preactivation: true

dataset_cfg:
     dataset_path : "/mnt/ssd1/datasets/i48/minids"
     mode: "multi_stack"
     n_channels: 1
     binarize_labels: true
#     positive_class_value: 255
#     negative_class_value: 0
#     ignore_last_channel: false
#     n_output_classes: 3
#     class_values: [0, 1, 2, 255]
 #    background_value: 255

output_cfg:
#    output_path: "/mnt/ssd1/em_training"
    output_path: "/mnt/ssd2/train_spim/2d"
    output_mode: "multi_stack"
#    output_path: "/home/phil/Desktop/3d_multi_stack_test_out"
    #descriptor_path: "/home/phil/Scrivania/single_images_test_descr"
#    descriptor_path: "/mnt/ssd1/em_training/descr"

data_augmentation_cfg:
    debug_mode: false
    single_thread:  true
    threads: 20
    buffer_size : 1000
    shuffle: false
    seed: 123
    # pre_crop_scales: [1.1, 1.1, 1.1]
    transform_cfg:
        spatial_transform:
            do_elastic_deform: false
            deformation_scale: [0.9, 1.0]
            do_rotation: true
            angle_x: [-0.314, 0.314]
            angle_y: [0, 6.38]
            p_rot_per_sample: 0.15
            do_scale: false
            scale: [0.95, 1.05]
            border_mode_data: "reflect"
            random_crop: false

        brightness_transform:
            mu: 0
            sigma: 0.1
            p_per_sample: 0.

        brightness_multiplicative_transform:
            multiplier_range: [0.9, 1.1]
            per_channel: true
            p_per_sample: 0.

        rot90_transform:
            p_per_sample: 0.
            num_rot : [1, 2]
#            axes: [0, 1, 2]

        mirror_transform:
            axes: [0, 1]

        gamma_transform:
            gamma_range: [0.9, 1.1]
            invert_image: false
            per_channel: true
            p_per_sample: 0.
#            retain_stats: true

        gaussian_noise_transform:
            noise_variance: [0, 0.00005]
            p_per_sample:  0.

        gaussian_blur_transform:
            p_per_sample: 0.
            blur_sigma: [1, 1.5]
            different_sigma_per_channel: true,
            p_per_channel: 1

performance_evaluation_cfg:
    window_size: [256, 256]
    batch_size:       20
    chunk_size:       20
    classification_threshold:   0.5
    add_empty_channel:          true
    enable_curves: false
    padding_mode: "reflect"
    to_8bit: true

callbacks_cfg:
    checkpoint:
        monitor:        "val_loss"
        verbose:        1
        save_best_only: false
        mode:           "min"

    csvlogger:
        append:     true
        separator: ";"

    reducelronplateau:
        factor:     0.1
        patience:   5
        min_lr:     0.00000000067
        verbose:    1

    # wandb:
    #     monitor: "val_loss"
    #     mode: "min"
    #     save_weights_only: false
    #     save_model: true


notes: ""

debug_cfg:
    test_datagen_inspector: false
    train_datagen_inspector: false
    val_datagen_inspector: false

tiled_predictor_cfg:
    extra_padding_windows: 2
#    window_overlap : [12, 12]
    tiling_mode: "drop_borders"
    to_segmentation: true
    n_threads: 1

instance_segmentation_cfg:
    enable_instance_segmentation: true
    kernel_size: [5,5,5]
    clear_borders: false
    distance_transform_threhsold: 0.2
    distance_transform_sampling: 5
    watershed_line: false
    bg_level: 10
