from neuroseg.tiledpredict.tp2d import TiledPredictor2D
from neuroseg.tiledpredict.tp2d import DataPredictor2D
from neuroseg.tiledpredict.tp3d import TiledPredictor3D
from neuroseg.tiledpredict.tp3d import DataPredictor3D
from neuroseg.tiledpredict.tp2d_single_images import SingleImagesDataPredictor

from neuroseg.tiledpredict.datapredictor import DataPredictor